# Generated by Django 3.1.1 on 2020-09-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_checked',
            field=models.DateTimeField(),
        ),
    ]
