# Generated by Django 3.1.1 on 2020-09-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0003_stock_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='low',
        ),
    ]
